---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: movie_fun_source

outputs:
- name: package-output

run:
  path: movie_fun_source/ci/tasks/package.sh

